In [29]:
import numpy as np


# Section 1: Array Creation


In [30]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", a)

1D Array:
 [1 2 3 4 5]


In [31]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", b)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [32]:
# Array of zeros and ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
print("\nArray of Zeros:\n", zeros)
print("\nArray of Ones:\n", ones)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
# Random arrays
rand_uniform = np.random.rand(2, 3)
rand_int = np.random.randint(1, 100, size=(3, 3))
print("\nRandom Uniform Array:\n", rand_uniform)
print("\nRandom Integer Array:\n", rand_int)


Random Uniform Array:
 [[0.59855399 0.08713615 0.99732449]
 [0.77034754 0.46285485 0.66093256]]

Random Integer Array:
 [[34 83 63]
 [92 61 42]
 [16 55 40]]


# ---------------------------
# Section 2: Indexing and Slicing
# ---------------------------

In [34]:

print("\nElement at index 2 in a:", a[2])
print("Slice of a (1:4):", a[1:4])
print("Last 2 elements of a:", a[-2:])


Element at index 2 in a: 3
Slice of a (1:4): [2 3 4]
Last 2 elements of a: [4 5]


In [35]:

# 2D indexing
print("\nElement at (1,2) in b:", b[1, 2])
print("Second row of b:", b[1])
print("First column of b:", b[:, 0])


Element at (1,2) in b: 6
Second row of b: [4 5 6]
First column of b: [1 4]


# ---------------------------
# Section 3: Array Operations
# ---------------------------

In [36]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])
print("\nAddition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [37]:
# Statistics
print("\nMean of x:", np.mean(x))
print("Median of x:", np.median(x))
print("Standard Deviation of x:", np.std(x))


Mean of x: 20.0
Median of x: 20.0
Standard Deviation of x: 8.16496580927726


# ---------------------------
# Section 4: Reshaping Arrays
# ---------------------------

In [38]:
c = np.array([[1, 2], [3, 4], [5, 6]])
print("\nOriginal c:\n", c)
c_reshaped = c.reshape((2, 3))
print("Reshaped c:\n", c_reshaped)

# Flatten
flattened = c.flatten()
print("Flattened c:", flattened)


Original c:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped c:
 [[1 2 3]
 [4 5 6]]
Flattened c: [1 2 3 4 5 6]


# ---------------------------
# Section 5: Broadcasting
# ---------------------------

In [39]:
d = np.array([[1], [2], [3]])
e = np.array([10, 20, 30])
print("\nBroadcasting Example:\n", d + e)



Broadcasting Example:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]



# ---------------------------
# Section 6: Boolean Indexing
# ---------------------------

In [40]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 15
print("\nMask:", mask)
print("Filtered Values:", arr[mask])



Mask: [False False False  True  True]
Filtered Values: [20 25]


# ---------------------------
# Section 7: Mini ML Preprocessing - Normalization
# ---------------------------

In [41]:
# Fake dataset: [Height, Weight, Age]
data = np.array([
    [160, 55, 22],
    [170, 65, 25],
    [180, 75, 28],
    [175, 70, 30]
])
print("\nDataset:\n", data)

# Basic statistics
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

print("\nMean:", mean)
print("Standard Deviation:", std)

# Normalize the dataset (Z-score)
data_normalized = (data - mean) / std
print("\nNormalized Data:\n", data_normalized)


Dataset:
 [[160  55  22]
 [170  65  25]
 [180  75  28]
 [175  70  30]]

Mean: [171.25  66.25  26.25]
Standard Deviation: [7.39509973 7.39509973 3.03108891]

Normalized Data:
 [[-1.52127766 -1.52127766 -1.40213637]
 [-0.16903085 -0.16903085 -0.41239305]
 [ 1.18321596  1.18321596  0.57735027]
 [ 0.50709255  0.50709255  1.23717915]]


# ---------------------------
# Section 8: Teaser - Features & Target (for ML)
# ---------------------------


In [42]:
# Assume 0 = Non-athlete, 1 = Athlete
labels = np.array([0, 0, 1, 1])
features = data_normalized
target = labels

print("\nFeatures (Normalized):\n", features)
print("Target:\n", target)

# Preview: Calculate Euclidean distance between two samples
from numpy.linalg import norm
dist = norm(features[0] - features[2])
print("\nDistance between person 0 and 2:", dist)



Features (Normalized):
 [[-1.52127766 -1.52127766 -1.40213637]
 [-0.16903085 -0.16903085 -0.41239305]
 [ 1.18321596  1.18321596  0.57735027]
 [ 0.50709255  0.50709255  1.23717915]]
Target:
 [0 0 1 1]

Distance between person 0 and 2: 4.306615698609548
